### ISSUE TITLE
Total flights count

### ISSUE THREAD

**Issue by brandtamos** [AlbericTrancart/spacexstats#17]
A reddit user brought to my attention that we are showing 38 flights for falcon 9, but that should really be 37 because Amos-6 never flew. Right now the code just looks for missions with a status of "complete", but we maybe need a new status like "canceled" to be able to filter out situations like Amos-6.

**Comment by AlbericTrancart** [comment]
In that regard, does the CRS-7 RUD can be counted as a "valid flight"? We might want to consider both RUDs the same way, either by:

* not counting them as flights or
* by including Amos-6 as a flight (same as CRS-7) and showing a failure rate somewhere

**Comment by jhpratt** [comment]
I'll agree with that original user. I would say a flight is where a rocket leaves the ground, regardless of whether it made orbit.

For this, CRS-7 is a flight, but Amos-6 is not. They're both failures, but only CRS is a failure in flight.
