### ISSUE TITLE
"Reflown" count is incorrect

### ISSUE THREAD

**Issue by brandtamos** [AlbericTrancart/spacexstats#22]
A reddit user pointed out that "Reflown" is showing "2" at the moment, but obviously that should just be "1". This must have happened after I added B1029 as the re-used booster for BulgariaSat-1. I checked in the StatisiticResultBuilder file, and it appears that the sql statement run doesn't filter out based on mission status.

I figured we just need to join in the "missions" table and filter based on missions.outcome = "Success"

**Comment by jhpratt** [comment]
This query [here](https://github.com/AlbericTrancart/spacexstats/blob/master/app/Services/StatisticResultBuilder.php#L158) is what needs to be changed.

Working on some other stuff right now, otherwise I'd do it.
